### ISSUE TITLE
Could not pass playerInteractEvent .

### ISSUE THREAD

**Issue by armagadon159753** [Frago9876543210/Inv-Menu#1]
![screenshot_2017-07-18-19-22-52](https://user-images.githubusercontent.com/25569806/28330699-d1d32b00-6bee-11e7-9791-c9e5d39acc5e.png)

**Comment by Frago9876543210** [comment]
@armagadon159753 Ok, I'll update to api 3, but not everything can work correctly.

**Comment by armagadon159753** [comment]
Ok
