### ISSUE TITLE
Help me, please

### ISSUE THREAD

**Issue by 3P-PocketMine** [Frago9876543210/Inv-Menu#13]
Can I get a translation for the version below 1.2 and an example of using the createChest function, thanks

**Comment by PotatoeTrainYT** [comment]
https://github.com/Frago9876543210/Inv-Menu/issues/12

**Comment by 3P-PocketMine** [comment]
@PotatoeTrainYT 
Why is there another thing between an apple and a chest - 0?

**Comment by PotatoeTrainYT** [comment]
that sets air, for an example that u can do case 2 without doing case 1
