### ISSUE TITLE
Error! Help!

### ISSUE THREAD

**Issue by 3P-PocketMine** [Frago9876543210/Inv-Menu#14]
ERROR:
[18:23:03] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'Pechenka v1': Class pocketmine\network\mcpe\protocol\types\WindowTypes not found on Pechenka\listener\ShopListener
CODE:
 public function addMenu($d){
        $items = [Item::get($this->settsing->get("firstmenu"), 0, 1), Item::get($this->settsing->get("secondmenu"), 0, 1), Item::get($this->settsing->get("threemenu"), 0, 1)];
        $this->invmenu->createChest($d, [Item::get($this->settsing->get("firstmenu"), 0, 1), Item::get($this->settsing->get("secondmenu"), 0, 1), Item::get($this->settsing->get("threemenu"), 0, 1)], 3598, "Меню");
    }

  public function listenDamage(EntityDamageEvent $event)
    {
        if ($event instanceof EntityDamageByEntityEvent) {
            $entity = $event->getEntity();
            $d = $event->getDamager();
            if ($entity instanceof Human and $d instanceof Player) {
                if ($this->plugin->hasNPC($entity->getNameTag())) {
                    $event->setCancelled();
                    $this->plugin->addMenu($d);
                    $this->plugin->addMassiv($d->getName(), $entity->getNameTag());
                }
            }
        }
    }

I'm testing on version 1.1. Translated from 1.2 to the version below (cleaned typing). Probably a bug in that that I crookedly translated, if yes - I will ask to throw off a plugin for 1.1

**Comment by Frago9876543210** [comment]
Plugin support 1.2 only, but you can use ```git checkout e744dbea5c172dd2b59e677aca0c09748ef04329```

**Comment by PotatoeTrainYT** [comment]
frago add me on discord, PotatoeTheDev#6123
